[package]
name = "pallet-grandpa"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME pallet for GRANDPA finality gadget"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
log = { workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
frame = { workspace = true, features = ["runtime"] }
pallet-authorship = { workspace = true }
pallet-session = { workspace = true }
sp-application-crypto = { features = ["serde"], workspace = true }
sp-consensus-grandpa = { features = ["serde"], workspace = true }
sp-session = { workspace = true }
sp-staking = { features = ["serde"], workspace = true }
sp-weights = { workspace = true }

[dev-dependencies]
frame = { workspace = true, features = ["runtime"] }
finality-grandpa = { features = [
	"derive-codec",
], workspace = true, default-features = true }
frame-election-provider-support = { workspace = true, default-features = true }
pallet-balances = { workspace = true, default-features = true }
pallet-offences = { workspace = true, default-features = true }
pallet-staking = { workspace = true, default-features = true }
pallet-staking-reward-curve = { workspace = true, default-features = true }
pallet-timestamp = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"scale-info/std",
	"sp-application-crypto/std",
	"sp-consensus-grandpa/std",
	"sp-session/std",
	"sp-staking/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
]
